In [10]:
import numpy as np

# X = (hours sleeping, hours studying), y = score on test
X = np.array(([2, 9], [1, 5], [3, 6]), dtype=float)
y = np.array(([92], [86], [89]), dtype=float)
xPredicted = np.array(([4,8]), dtype=float)

# scale units
X = X/np.amax(X, axis=0) # maximum of X array
xPredicted = xPredicted/np.amax(xPredicted, axis=0) # maximum of xPredicted (our input data for the prediction)
y = y/100 # max test score is 100

In [11]:
class Neural_Network(object):
    def __init__(self):
        #parameters
        self.inputSize = 2
        self.outputSize = 1
        self.hiddenSize = 3
        
        #weights
        self.W1 = np.random.randn(self.inputSize, self.hiddenSize)
        self.W2 = np.random.randn(self.hiddenSize, self.outputSize)
    
    def forward(self, X):
        # forward propagation through our network
        self.z = np.dot(X, self.W1)
        self.z2 = self.sigmoid(self.z)
        self.z3 = np.dot(self.z2, self.W2)
        o = self.sigmoid(self.z3)
        return o
    
    def sigmoid(self, s):
        # activation function
        return 1/(1+np.exp(-s))
    
    def sigmoidPrime(self, s):
        # derivative of sigmoid
        return s * (1 - s)
    
    def backward(self, X, y, o):
        # backward propagate through the network
        self.o_error = y - o # error in output
        self.o_delta = self.o_error*self.sigmoidPrime(o) # applying derivative of sigmoid to error
    
        self.z2_error = self.o_delta.dot(self.W2.T)
        self.z2_delta = self.z2_error*self.sigmoidPrime(self.z2)
        
        self.W1 += X.T.dot(self.z2_delta)
        self.W2 += self.z2.T.dot(self.o_delta)
        
    def train(self, X, y):
        o = self.forward(X)
        self.backward(X, y, o)
    
    def saveWeights(self):
        np.savetxt("w1.txt", self.W1, fmt="%s")
        np.savetxt("w2.txt", self.W2, fmt="%s")
    
    def predict(self):
        print("Predicted data based on trained weights: ")
        print("Input (scaled): \n" + str(xPredicted))
        print("Output: \n" + str(self.forward(xPredicted)))

In [12]:
NN = Neural_Network()

# defining our output
# o = NN.forward(X)

# print("Predicted Output: \n" + str(o))
# print("Actual Output: \n" + str(y))

In [14]:
for i in range(1000):
    print("# " + str(i) + "\n")
    print("Input (scaled): \n" + str(X)) 
    print("Actual Output: \n" + str(y)) 
    print("Predicted Output: \n" + str(NN.forward(X))) 
    print("Loss: \n" + str(np.mean(np.square(y - NN.forward(X))))) # mean sum squared loss
    print("\n")
    NN.train(X, y)

NN.saveWeights()
NN.predict()

# 0

Input (scaled): 
[[ 0.66666667  1.        ]
 [ 0.33333333  0.55555556]
 [ 1.          0.66666667]]
Actual Output: 
[[ 0.92]
 [ 0.86]
 [ 0.89]]
Predicted Output: 
[[ 0.24360133]
 [ 0.22738902]
 [ 0.26198749]]
Loss: 
0.417370509923


# 1

Input (scaled): 
[[ 0.66666667  1.        ]
 [ 0.33333333  0.55555556]
 [ 1.          0.66666667]]
Actual Output: 
[[ 0.92]
 [ 0.86]
 [ 0.89]]
Predicted Output: 
[[ 0.29186677]
 [ 0.26864959]
 [ 0.30990064]]
Loss: 
0.360253976709


# 2

Input (scaled): 
[[ 0.66666667  1.        ]
 [ 0.33333333  0.55555556]
 [ 1.          0.66666667]]
Actual Output: 
[[ 0.92]
 [ 0.86]
 [ 0.89]]
Predicted Output: 
[[ 0.33801113]
 [ 0.31047982]
 [ 0.35482918]]
Loss: 
0.309030425514


# 3

Input (scaled): 
[[ 0.66666667  1.        ]
 [ 0.33333333  0.55555556]
 [ 1.          0.66666667]]
Actual Output: 
[[ 0.92]
 [ 0.86]
 [ 0.89]]
Predicted Output: 
[[ 0.37950238]
 [ 0.35083726]
 [ 0.39474653]]
Loss: 
0.265553456298


# 4

Input (scaled): 
[[ 0.66666667  1.        ]
 [ 


# 135

Input (scaled): 
[[ 0.66666667  1.        ]
 [ 0.33333333  0.55555556]
 [ 1.          0.66666667]]
Actual Output: 
[[ 0.92]
 [ 0.86]
 [ 0.89]]
Predicted Output: 
[[ 0.89517776]
 [ 0.87380766]
 [ 0.89649892]]
Loss: 
0.000283010296773


# 136

Input (scaled): 
[[ 0.66666667  1.        ]
 [ 0.33333333  0.55555556]
 [ 1.          0.66666667]]
Actual Output: 
[[ 0.92]
 [ 0.86]
 [ 0.89]]
Predicted Output: 
[[ 0.89523484]
 [ 0.87385018]
 [ 0.8965494 ]]
Loss: 
0.000282678393168


# 137

Input (scaled): 
[[ 0.66666667  1.        ]
 [ 0.33333333  0.55555556]
 [ 1.          0.66666667]]
Actual Output: 
[[ 0.92]
 [ 0.86]
 [ 0.89]]
Predicted Output: 
[[ 0.89529032]
 [ 0.87389117]
 [ 0.89659831]]
Loss: 
0.000282356863798


# 138

Input (scaled): 
[[ 0.66666667  1.        ]
 [ 0.33333333  0.55555556]
 [ 1.          0.66666667]]
Actual Output: 
[[ 0.92]
 [ 0.86]
 [ 0.89]]
Predicted Output: 
[[ 0.89534426]
 [ 0.87393069]
 [ 0.8966457 ]]
Loss: 
0.000282045087186


# 139

Input (scaled): 
[[ 0.66

 [ 1.          0.66666667]]
Actual Output: 
[[ 0.92]
 [ 0.86]
 [ 0.89]]
Predicted Output: 
[[ 0.89758268]
 [ 0.87446629]
 [ 0.89809504]]
Loss: 
0.000259113119655


# 275

Input (scaled): 
[[ 0.66666667  1.        ]
 [ 0.33333333  0.55555556]
 [ 1.          0.66666667]]
Actual Output: 
[[ 0.92]
 [ 0.86]
 [ 0.89]]
Predicted Output: 
[[ 0.89758843]
 [ 0.87446038]
 [ 0.89809529]]
Loss: 
0.000258971619535


# 276

Input (scaled): 
[[ 0.66666667  1.        ]
 [ 0.33333333  0.55555556]
 [ 1.          0.66666667]]
Actual Output: 
[[ 0.92]
 [ 0.86]
 [ 0.89]]
Predicted Output: 
[[ 0.89759415]
 [ 0.87445446]
 [ 0.89809552]]
Loss: 
0.000258830254279


# 277

Input (scaled): 
[[ 0.66666667  1.        ]
 [ 0.33333333  0.55555556]
 [ 1.          0.66666667]]
Actual Output: 
[[ 0.92]
 [ 0.86]
 [ 0.89]]
Predicted Output: 
[[ 0.89759985]
 [ 0.87444852]
 [ 0.89809573]]
Loss: 
0.00025868902359


# 278

Input (scaled): 
[[ 0.66666667  1.        ]
 [ 0.33333333  0.55555556]
 [ 1.          0.66666667]]
Actua

Input (scaled): 
[[ 0.66666667  1.        ]
 [ 0.33333333  0.55555556]
 [ 1.          0.66666667]]
Actual Output: 
[[ 0.92]
 [ 0.86]
 [ 0.89]]
Predicted Output: 
[[ 0.89833948]
 [ 0.87353761]
 [ 0.89804193]]
Loss: 
0.000239039132273


# 427

Input (scaled): 
[[ 0.66666667  1.        ]
 [ 0.33333333  0.55555556]
 [ 1.          0.66666667]]
Actual Output: 
[[ 0.92]
 [ 0.86]
 [ 0.89]]
Predicted Output: 
[[ 0.89834413]
 [ 0.87353171]
 [ 0.89804141]]
Loss: 
0.000238915993155


# 428

Input (scaled): 
[[ 0.66666667  1.        ]
 [ 0.33333333  0.55555556]
 [ 1.          0.66666667]]
Actual Output: 
[[ 0.92]
 [ 0.86]
 [ 0.89]]
Predicted Output: 
[[ 0.89834878]
 [ 0.87352582]
 [ 0.89804088]]
Loss: 
0.000238792963097


# 429

Input (scaled): 
[[ 0.66666667  1.        ]
 [ 0.33333333  0.55555556]
 [ 1.          0.66666667]]
Actual Output: 
[[ 0.92]
 [ 0.86]
 [ 0.89]]
Predicted Output: 
[[ 0.89835343]
 [ 0.87351994]
 [ 0.89804036]]
Loss: 
0.000238670041959


# 430

Input (scaled): 
[[ 0.66666667  

 [ 1.          0.66666667]]
Actual Output: 
[[ 0.92]
 [ 0.86]
 [ 0.89]]
Predicted Output: 
[[ 0.89902194]
 [ 0.87269129]
 [ 0.89795903]]
Loss: 
0.000221498027167


# 579

Input (scaled): 
[[ 0.66666667  1.        ]
 [ 0.33333333  0.55555556]
 [ 1.          0.66666667]]
Actual Output: 
[[ 0.92]
 [ 0.86]
 [ 0.89]]
Predicted Output: 
[[ 0.89902627]
 [ 0.87268604]
 [ 0.89795846]]
Loss: 
0.000221389982807


# 580

Input (scaled): 
[[ 0.66666667  1.        ]
 [ 0.33333333  0.55555556]
 [ 1.          0.66666667]]
Actual Output: 
[[ 0.92]
 [ 0.86]
 [ 0.89]]
Predicted Output: 
[[ 0.89903061]
 [ 0.87268079]
 [ 0.8979579 ]]
Loss: 
0.000221282028603


# 581

Input (scaled): 
[[ 0.66666667  1.        ]
 [ 0.33333333  0.55555556]
 [ 1.          0.66666667]]
Actual Output: 
[[ 0.92]
 [ 0.86]
 [ 0.89]]
Predicted Output: 
[[ 0.89903494]
 [ 0.87267555]
 [ 0.89795733]]
Loss: 
0.000221174164445


# 582

Input (scaled): 
[[ 0.66666667  1.        ]
 [ 0.33333333  0.55555556]
 [ 1.          0.66666667]]
Actu



# 752

Input (scaled): 
[[ 0.66666667  1.        ]
 [ 0.33333333  0.55555556]
 [ 1.          0.66666667]]
Actual Output: 
[[ 0.92]
 [ 0.86]
 [ 0.89]]
Predicted Output: 
[[ 0.89974914]
 [ 0.87183517]
 [ 0.89785674]]
Loss: 
0.000203965627803


# 753

Input (scaled): 
[[ 0.66666667  1.        ]
 [ 0.33333333  0.55555556]
 [ 1.          0.66666667]]
Actual Output: 
[[ 0.92]
 [ 0.86]
 [ 0.89]]
Predicted Output: 
[[ 0.89975316]
 [ 0.87183056]
 [ 0.89785612]]
Loss: 
0.000203871739898


# 754

Input (scaled): 
[[ 0.66666667  1.        ]
 [ 0.33333333  0.55555556]
 [ 1.          0.66666667]]
Actual Output: 
[[ 0.92]
 [ 0.86]
 [ 0.89]]
Predicted Output: 
[[ 0.89975719]
 [ 0.87182596]
 [ 0.89785551]]
Loss: 
0.000203777925182


# 755

Input (scaled): 
[[ 0.66666667  1.        ]
 [ 0.33333333  0.55555556]
 [ 1.          0.66666667]]
Actual Output: 
[[ 0.92]
 [ 0.86]
 [ 0.89]]
Predicted Output: 
[[ 0.89976121]
 [ 0.87182136]
 [ 0.8978549 ]]
Loss: 
0.00020368418357


# 756

Input (scaled): 
[[ 0.66

 [ 1.          0.66666667]]
Actual Output: 
[[ 0.92]
 [ 0.86]
 [ 0.89]]
Predicted Output: 
[[ 0.90062212]
 [ 0.87087082]
 [ 0.8977109 ]]
Loss: 
0.000184378325466


# 980

Input (scaled): 
[[ 0.66666667  1.        ]
 [ 0.33333333  0.55555556]
 [ 1.          0.66666667]]
Actual Output: 
[[ 0.92]
 [ 0.86]
 [ 0.89]]
Predicted Output: 
[[ 0.90062579]
 [ 0.87086691]
 [ 0.89771023]]
Loss: 
0.000184299075554


# 981

Input (scaled): 
[[ 0.66666667  1.        ]
 [ 0.33333333  0.55555556]
 [ 1.          0.66666667]]
Actual Output: 
[[ 0.92]
 [ 0.86]
 [ 0.89]]
Predicted Output: 
[[ 0.90062946]
 [ 0.870863  ]
 [ 0.89770955]]
Loss: 
0.000184219882238


# 982

Input (scaled): 
[[ 0.66666667  1.        ]
 [ 0.33333333  0.55555556]
 [ 1.          0.66666667]]
Actual Output: 
[[ 0.92]
 [ 0.86]
 [ 0.89]]
Predicted Output: 
[[ 0.90063314]
 [ 0.87085909]
 [ 0.89770888]]
Loss: 
0.000184140745456


# 983

Input (scaled): 
[[ 0.66666667  1.        ]
 [ 0.33333333  0.55555556]
 [ 1.          0.66666667]]
Actu